CREATE DATABASE examonline

CREATE TABLE Teacher (
id VARCHAR(10) PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
passwd VARCHAR(64) NOT NULL,
isAdmin BOOLEAN NOT NULL
);

CREATE TABLE Exam(
id INT(4) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
SUBJECT VARCHAR(20) NOT NULL,
starttime DATETIME NOT NULL,
endtime DATETIME NOT NULL,
state VARCHAR(10) NOT NULL DEFAULT "created",
t_id VARCHAR(10) NOT NULL,
CONSTRAINT fk_t_id FOREIGN KEY(t_id) REFERENCES Teacher(id) on delete cascade
)

CREATE TABLE Student(
id VARCHAR(10) NOT NULL,
NAME VARCHAR(20) NOT NULL,
ip VARCHAR(20) NOT NULL DEFAULT "0.0.0.0",
clazz VARCHAR(10) NOT NULL,
e_id INT(4) UNSIGNED ZEROFILL NOT NULL,
CONSTRAINT pk_s_id PRIMARY KEY(id,e_id),
CONSTRAINT fk_e_id FOREIGN KEY(e_id) REFERENCES Exam(id) on delete cascade
)

CREATE TABLE Question (
id INT(8) AUTO_INCREMENT PRIMARY KEY,
number INT(3) NOT NULL,
title VARCHAR(200) NOT NULL,
TYPE VARCHAR(20) NOT NULL,
selection VARCHAR(100) NOT NULL,
answer VARCHAR(50) NOT NULL,
e_id INT(4) UNSIGNED ZEROFILL NOT NULL,
score INT(2) default 1,
CONSTRAINT fk_q_id FOREIGN KEY(e_id) REFERENCES Exam(id) on delete cascade
)